.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. clashic_qt test_clashic_qt
clean: FORCE
	$(MAKE) -C .. clashic_qt_clean test_clashic_qt_clean
check: FORCE
	$(MAKE) -C .. test_clashic_qt_check
clashic-qt clashic-qt.exe: FORCE
	 $(MAKE) -C .. clashic_qt
