.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. core_qt test_core_qt
clean: FORCE
	$(MAKE) -C .. core_qt_clean test_core_qt_clean
check: FORCE
	$(MAKE) -C .. test_core_qt_check
core-qt core-qt.exe: FORCE
	 $(MAKE) -C .. core_qt
